name: Java CI with Maven

on:
  push:
    branches: [ 'master', 'development', 'feature-*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install XVFB
      run: sudo apt-get update && sudo apt-get install -y xvfb
    - name: Build with Maven using XVFB
      run: xvfb-run mvn -B package --file pom.xml